default_platform(:ios)

platform :ios do
  desc 'Description of what the lane does'
  lane :beta do
    automatic_code_signing(
      targets: "Vertex",
      code_sign_identity: ENV['CODE_SIGN_IDENTITY'],
      profile_name: ENV['CODE_SIGN_PROFILE_NAME'],
      use_automatic_signing: false
    )
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      timeout: 1800
    )
    match(
      type: 'adhoc',
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      readonly: true
    )
    gym(
      configuration: "Release",
      scheme: "Vertex",
      export_method: "ad-hoc",
      output_directory: "./build/ipa/",
      output_name: "Vertex.ipa",
      include_bitcode: false,
      export_options: {
        compileBitcode: false,
        uploadBitcode: false
      }
    )
    automatic_code_signing(
      targets: "Vertex",
      code_sign_identity: 'iPhone Developer',
      profile_name: '',
      use_automatic_signing: true
    )
  end
end
